### PR TITLE
backend/drive: add flag for keep revision forever - fixes #1525

### LINKED ISSUE #1525: Google Drive: Add flag for keepRevisionForever
Google Drive by default keeps previous versions of a file for 30 days.
However they can be kept forever if you set keepRevisionForever to true.
https://developers.google.com/drive/v3/web/manage-revisions

This would be really useful for certain documents where I may need to revert to a previous version.
While I do of course have other backups, sometimes it's just easier to revert via Drive.

Would it be possible to add this?
Thanks.

> What is your rclone version (eg output from `rclone -V`)
1.36
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Win10, 64
> Which cloud storage system are you using? (eg Google Drive)
Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy file gd: --drive-keep-revision
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2017/07/12 09:45:38 Fatal error: unknown flag: --drive-keep-revision

### PR DESCRIPTION
**Pull request by lewapm**

### CODE REVIEW

File: backend/drive/drive.go [hunk 1]
```diff
@@ -1014,7 +1015,7 @@ func (f *Fs) Copy(src fs.Object, remote string) (fs.Object, error) {
 
 	var info *drive.File
 	err = o.fs.pacer.Call(func() (bool, error) {
-		info, err = o.fs.svc.Files.Copy(srcObj.id, createInfo).Fields(googleapi.Field(partialFields)).SupportsTeamDrives(f.isTeamDrive).Do()
```
Comment (ncw) [inline backend/drive/drive.go]: Does this need to be on the upload calls too?

File: fs/test_all.log [hunk 2]
```diff
@@ -0,0 +1 @@
+bash: test_all: nie znaleziono polecenia
```
Comment (ncw) [inline fs/test_all.log]: Can you remove this from the commit

File: test.log [hunk 3]
```diff
@@ -0,0 +1,6125 @@
+?   	github.com/ncw/rclone	[no test files]
```
Comment (ncw) [inline test.log]: Can you remove this too please!

**Comment by ncw** [comment]
Can you squash this please and remove the `test.log` and `fs/test_all.log` files please?

```
    backend/drive: add flag for keep revision forever - fixes #1525

 backend/drive/drive.go  |   29 +-
 backend/drive/upload.go |    3 +
 docs/content/drive.md   |    4 +
 fs/test_all.log         |    0
 test.log                | 6124 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

I plan to merge after the weekend after I release 1.42 so the feature has some time for testing before I make a release.

**Comment by ncw** [comment]
Thank you for that :-)
