### PR TITLE
drive: fix single Drive Document as FS root

### LINKED ISSUE #1772: Unable to copy a single file from Google Drive
Hi, Nick!

I am using `rclone` (`rclone-v1.38-linux-amd64.zip`) on Debian Jessie but I am not able to copy a single file:

```
$ ./rclone ls remote:Educ.ar
     4629 IDC-EQUIPAMIENTO.xlsx
```

```
$ ./rclone copy remote:Educ.ar/IDC-EQUIPAMIENTO.xlsx .
2017/10/25 13:53:58 ERROR : : error reading source directory: directory not found
2017/10/25 13:53:58 ERROR : Attempt 1/3 failed with 1 errors
2017/10/25 13:53:58 ERROR : : error reading source directory: directory not found
2017/10/25 13:53:58 ERROR : Attempt 2/3 failed with 1 errors
2017/10/25 13:53:58 ERROR : : error reading source directory: directory not found
2017/10/25 13:53:58 ERROR : Attempt 3/3 failed with 1 errors
```

Maybe I'm missing something?

Thanks in advance.

Kind regards,
Daniel

### PR DESCRIPTION
**Pull request by B4dM4n**
Allow using Drive Documents as FS root by doing a direcoty list during NewFS.

Fixes #1772

### CODE REVIEW

File: backend/drive/drive.go [hunk 1]
```diff
@@ -507,13 +507,19 @@ func NewFs(name, path string) (fs.Fs, error) {
...
+		entries, err := newF.List("")
 		if err != nil {
-			// File doesn't exist so return old f
+			// unable to list folder so return old f
 			return f, nil
 		}
-		// return an error with an fs which points to the parent
-		return &newF, fs.ErrorIsFile
+		for _, e := range entries {
+			if _, isObject := e.(fs.Object); isObject && e.Remote() == remote {
```
Comment (ncw) [inline backend/drive/drive.go]: I think this should probably check `e.Remote() == remote` first and do `something` if it was a directory too.

That will help with  #1675

That issue is caused by a bug in drive which causes searching for directories with an accent not to be found so this branch of code will be entered when the thing missing is a directory too sometimes.

It isn't a 100% fix for #1675 but it would help.

Exactly what `something` should be I'm not sure, it it will probably involve poking the directory ID into directory cache...

I'm going to merge this as-is as it doesn't make #1675 any worse - do you fancy sending a follow-up for that issue?

Comment (B4dM4n) [reply backend/drive/drive.go]: I looked into the issue and think the workaround should not be handled in `NewFS`.
The workaround i propose for #1675 handles all directory lookup's and not just the root case.

Comment (ncw) [reply backend/drive/drive.go]: OK that is fine with me :-)
