### PR TITLE
march: return errors when listing dirs

### LINKED ISSUE #3172: Behaviour for HTTP API is not the same as with CLI API
#### What is the problem you are having with rclone?

Sending requests that should fail (missing local dir, access denied to remote, etc.) to rclone HTTP server are not failing. They end with empty object and 200 code result. Tested with both curl and rclone rc.

Example:

```
a> rclone rcd -vv --rc-no-auth
b> rclone rc sync/move srcFs=/non-existent/ dstFs=created-but-inaccessible-remote:bucket/test
{}
b> curl --verbose -H "Content-Type: application/json" -d '{"srcFs":"local-dir-that-exists", "dstFs":"created-but-inaccessible-remote:bucket/test"}' http://localhost:5572/sync/move
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5572 (#0)
> POST /sync/move HTTP/1.1
> Host: localhost:5572
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 65
> 
* upload completely sent off: 65 out of 65 bytes
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: 
< Access-Control-Allow-Origin: *
< Date: Tue, 07 May 2019 08:11:03 GMT
< Content-Length: 3
< Content-Type: text/plain; charset=utf-8
< 
{}

```

Same request made with CLI is reporting an error (with retries) and exiting with `1`. I've taken a look at the code and it seems that CLI calls are wrapped with `cmd.Run` function which integrates with `accounting` and has retries. This functionality is not available within handler for HTTP server so requests never fail. Although available in the server error logs.

Which leads me to another "API design" question, why is for example `sync.MoveDir` not returning an error on failure? It seems currently the only way to know if there was a failure is to use `accounting.Stats`. From how these top level functions are used it seems like entire call chain depends on these top level functions to return errors.

#### What is your rclone version (output from `rclone version`)

rclone v1.47.0-DEV
- os/arch: linux/amd64
- go version: go1.12.4

Ubuntu 18.04

####  Which cloud storage system are you using? (eg Google Drive)

AWS S3 but it shouldn't matter to this issue.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

HTTP Server logs:

```
2019/05/07 10:28:09 DEBUG : rclone: Version "v1.47.0-DEV" starting with parameters ["rclone" "rcd" "-vv" "--rc-no-auth"]
2019/05/07 10:28:09 NOTICE: Serving remote control on http://127.0.0.1:5572/
2019/05/07 10:28:14 DEBUG : rc: "sync/move": with parameters map[dstFs:bla:bucket/test srcFs:/non-existent/]
2019/05/07 10:28:14 DEBUG : Using config file from "/home/alek/.config/rclone/rclone.conf"
2019/05/07 10:28:15 ERROR : S3 bucket bucket path test/: Failed to update region for bucket: reading bucket location failed: AccessDenied: Access Denied
	status code: 403, request id: 5F13BD3082D862ED, host id: FlUy7pvhPWARqV4qVNBGRhKbrIykPXQnFAfRoU/6CK6HGs3qyWaZq/u57YLYOjqbn0yAa0WyoKM=
2019/05/07 10:28:15 ERROR : S3 bucket bucket path test/: Failed to update region for bucket: reading bucket location failed: AccessDenied: Access Denied
	status code: 403, request id: F45BAF0FA7E4A5D9, host id: SRxpFTaW90nTzWMToU5XBAeHI4lepEBM3mtTJrBwHx2L99FMQhqz2rLEtrcX+qDzKm6bcPx4u4g=
2019/05/07 10:28:15 ERROR : : error reading source directory: directory not found
2019/05/07 10:28:15 INFO  : S3 bucket bucket path test/: Waiting for checks to finish
2019/05/07 10:28:15 INFO  : S3 bucket bucket path test/: Waiting for transfers to finish
2019/05/07 10:28:15 DEBUG : rc: "sync/move": reply map[]: <nil>
2019/05/07 10:28:57 DEBUG : rc: "sync/move": with parameters map[dstFs:bla:scylla-manager-aleksandar/bash srcFs:tmp]
2019/05/07 10:28:57 ERROR : : error reading source directory: directory not found
2019/05/07 10:28:57 INFO  : S3 bucket scylla-manager-aleksandar path bash/: Waiting for checks to finish
2019/05/07 10:28:57 INFO  : S3 bucket scylla-manager-aleksandar path bash/: Waiting for transfers to finish
2019/05/07 10:28:57 DEBUG : rc: "sync/move": reply map[]: <nil>
```

### PR DESCRIPTION
**Pull request by ajankovic**
#### Was the change discussed in an issue or in the forum before?

Partially fixes #3172

#### What is the purpose of this change?

As described in linked issue errors in file system access are not returned when copying/moving. This change corrects that by catching any listing errors.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [ ] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

**Comment by ncw** [comment]
The build for this is failing on go1.9

```
# github.com/ncw/rclone/fs/march
fs/march/multierror.go:29:8: undefined: strings.Builder
```

I try to keep support for 2 years worth of go releases so that rclone can keep building for distros which are a bit behind.

**Comment by ajankovic** [comment]
Build failure is now different and vague I guess it needs another run.

File: fs/march/multierror.go [hunk 1]
```diff
@@ -0,0 +1,40 @@
+package march
+
+import (
+	"bytes"
+	"fmt"
+	"sync"
+)
+
+type multierror struct {
```
Comment (mmatczuk) [inline fs/march/multierror.go]: Why do we need a new multierror type? 

How about using an existing package like one from Uber or HashiCorp?

File: fs/march/march.go [hunk 2]
```diff
@@ -122,6 +122,7 @@ func (m *March) Run() {
 		dstDepth = fs.MaxLevel
 	}
 
+	merr := &multierror{}
```
Comment (mmatczuk) [inline fs/march/march.go]: If you used `github.com/uber-go/multierr` you could avoid allocation here.

File: fs/march/multierror.go (hunk 1 above)
Comment (ajankovic) [reply fs/march/multierror.go]: We need protection for concurrent use I don't think those packages provide that?

File: fs/march/march.go (hunk 2 above)
Comment (ajankovic) [reply fs/march/march.go]: What about concurrent usage needed below?

File: fs/march/multierror.go (hunk 1 above)
Comment (ncw) [reply fs/march/multierror.go]: I think I'd be happy just showing the last error (or the first).  More than a couple of errors are going to make the error messages unreadable.

**Comment by ajankovic** [comment]
Ok I replaced multierror with first occurring error and error count.

PTAL

File: fs/march/march.go [hunk 3]
```diff
@@ -178,6 +192,11 @@ func (m *March) Run() {
 	traversing.Wait()
 	close(in)
 	wg.Wait()
+
+	if errCount > 1 {
+		return fmt.Errorf("%+v (and %d others)", jobError, errCount-1)
```
Comment (ncw) [inline fs/march/march.go]: Can you make that something like `return errors.Wrapf(err, "march failed with %d errors: first error", errCount)` - rclone uses pkg/errors for error annotations and that will enable consumers to unwrap the error.

File: fs/march/march.go [hunk 4]
```diff
@@ -3,6 +3,7 @@ package march
 
 import (
 	"context"
+	"github.com/pkg/errors"
```
Comment (golangcibot) [inline fs/march/march.go]: File is not `goimports`-ed (from `goimports`)
```suggestion

```

**Comment by ncw** [comment]
That is perfect now - thank you very much :-)

I'll merge now.
