### PR TITLE
load config file only on first access (closes #1659, closes #2096)

### LINKED ISSUE #1659: version command fails if config file can't be read
rclone's version command fails if its config file can't be read.

Actual

    $ rclone -V
    2017/09/05 22:53:10 Failed to load config file "/home/paul/.config/rclone/rclone.conf": open /home/paul/.config/rclone/rclone.conf: permission denied

Expected

    $ rclone -V
    rclone v1.37

> What is your rclone version (eg output from `rclone -V`)
1.3.7

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux, 64 bit

> Which cloud storage system are you using? (eg Google Drive)
n/a

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -V

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

    2017/09/05 22:54:41 Failed to load config file "/home/paul/.config/rclone/rclone.conf": open /home/paul/.config/rclone/rclone.conf: permission denied

### LINKED ISSUE #2096: --version should not fail due to rclone.conf
> What is your rclone version (eg output from `rclone -V`)

rclone v1.39-DEV
- os/arch: freebsd/amd64
- go version: go1.9.3

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

FreeBSD

> Which cloud storage system are you using? (eg Google Drive)

n/a

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

My rclone.conf is owned by root for some reason.
```
ls -l $HOME/.rclone.conf
-rw-------  1 root  kcwu  937 Feb 26 14:19 /home/kcwu/.rclone.conf
```

Then `rclone -V` will fail with normal user permission.
```
$ rclone -V
2018/02/26 14:55:38 Failed to load config file "/home/kcwu/.rclone.conf": open /home/kcwu/.rclone.conf: permission denied
```

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

I expect "-V" should never fail for any reason.

### PR DESCRIPTION
**Pull request by breunigs**
Let's see if the tests pass also on CI. 

The patch delays loading the config file until the config is accessed for the first time. This allows `rclone help` and `rclone --version` to succeed (note: `rclone --help` always worked, even without the patch. It seems that cobra skips the initialization/`preRun` handlers in this case).

Ideally each command would decide on its own if it needs the config or not, but I could not find a way to do that without putting `LoadConfig()` into almost every subcommand.

### CODE REVIEW

File: fs/config/config.go [hunk 1]
```diff
@@ -61,7 +61,7 @@ const (
 // Global
 var (
 	// configData is the config file data structure
```
Comment (ncw) [inline fs/config/config.go]: Perhaps this for the comment? (it has the variable name wrong at the moment!)

```go
// configFile is the global config data structure. Don't use directly, use getConfigData()
```

Comment (breunigs) [reply fs/config/config.go]: ah, yes, good catch!
