### PR TITLE
Fix #3164 Onedrive skips files; add FsRootCollapse test

### LINKED ISSUE #3164: OneDrive can skip single file upload
#### What is the problem you are having with rclone?

When uploading a single file to a OneDrive folder, it can get skipped if the file already exists in the root folder and the destination folder does not exist.

This happens because [readMetaDataForPath](https://github.com/ncw/rclone/blob/b9e16b36e5208dc7460af59d9e75dc8234caca27/backend/onedrive/onedrive.go#L356) calls `f.dirCache.Get("")` and assumes the it got the right folder ID.

If `f.root` (`foldera` or `foldera/folderb` in the log below) does not exist, the returned folder ID is actually the drive root and `f.dirCache.foundRoot` is still false.

I assume the right function in this case should be `f.dirCache.FindRoot(false)` instead of `f.dirCache.Get("")`, but I'm not sure if this would break the issue in [onedrive.go#L379](https://github.com/ncw/rclone/blob/b9e16b36e5208dc7460af59d9e75dc8234caca27/backend/onedrive/onedrive.go#L379) again.

@Cnly any thoughts how this should be fixed?

#### What is your rclone version (output from `rclone version`)

`v1.47.0-032-gb9e16b36-beta`

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

`Linux Fabian-Desktop 5.0.9 #1-NixOS SMP Sat Apr 20 07:17:05 UTC 2019 x86_64 GNU/Linux`

####  Which cloud storage system are you using? (eg Google Drive)

OneDrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone copy a.txt TestOneDrive:foldera`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
% rclone copy -vv a.txt TestOneDrive:
2019/05/03 23:44:20 DEBUG : rclone: Version "v1.47.0-032-gb9e16b36-beta" starting with parameters ["rclone" "copy" "-vv" "a.txt" "TestOneDrive:"]
2019/05/03 23:44:20 DEBUG : Using config file from "/home/fabian/.config/rclone/rclone.conf"
2019/05/03 23:44:21 DEBUG : a.txt: Couldn't find file - need to transfer
2019/05/03 23:44:21 DEBUG : a.txt: Starting multipart upload
2019/05/03 23:44:22 DEBUG : a.txt: Uploading segment 0/29 size 29
2019/05/03 23:44:22 INFO  : a.txt: Copied (new)
2019/05/03 23:44:22 INFO  :
Transferred:   	        29 / 29 Bytes, 100%, 15 Bytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            1 / 1, 100%
Elapsed time:        1.8s

2019/05/03 23:44:22 DEBUG : 9 go routines active
2019/05/03 23:44:22 DEBUG : rclone: Version "v1.47.0-032-gb9e16b36-beta" finishing with parameters ["rclone" "copy" "-vv" "a.txt" "TestOneDrive:"]

% rclone copy -vv a.txt TestOneDrive:foldera
2019/05/03 23:44:35 DEBUG : rclone: Version "v1.47.0-032-gb9e16b36-beta" starting with parameters ["rclone" "copy" "-vv" "a.txt" "TestOneDrive:foldera"]
2019/05/03 23:44:35 DEBUG : Using config file from "/home/fabian/.config/rclone/rclone.conf"
2019/05/03 23:44:37 DEBUG : a.txt: Size and modification time the same (differ by -638.252406ms, within tolerance 1s)
2019/05/03 23:44:37 DEBUG : a.txt: Unchanged skipping
2019/05/03 23:44:37 INFO  :
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 1 / 1, 100%
Transferred:            0 / 0, -
Elapsed time:        1.3s

2019/05/03 23:44:37 DEBUG : 6 go routines active
2019/05/03 23:44:37 DEBUG : rclone: Version "v1.47.0-032-gb9e16b36-beta" finishing with parameters ["rclone" "copy" "-vv" "a.txt" "TestOneDrive:foldera"]

% rclone copy -vv a.txt TestOneDrive:foldera/folderb
2019/05/03 23:44:39 DEBUG : rclone: Version "v1.47.0-032-gb9e16b36-beta" starting with parameters ["rclone" "copy" "-vv" "a.txt" "TestOneDrive:foldera/folderb"]
2019/05/03 23:44:39 DEBUG : Using config file from "/home/fabian/.config/rclone/rclone.conf"
2019/05/03 23:44:41 DEBUG : a.txt: Size and modification time the same (differ by -638.252406ms, within tolerance 1s)
2019/05/03 23:44:41 DEBUG : a.txt: Unchanged skipping
2019/05/03 23:44:41 INFO  :
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 1 / 1, 100%
Transferred:            0 / 0, -
Elapsed time:        1.3s

2019/05/03 23:44:41 DEBUG : 6 go routines active
2019/05/03 23:44:41 DEBUG : rclone: Version "v1.47.0-032-gb9e16b36-beta" finishing with parameters ["rclone" "copy" "-vv" "a.txt" "TestOneDrive:foldera/folderb"]

% rclone tree TestOneDrive:foldera
2019/05/03 23:45:07 ERROR : : error listing: directory not found
2019/05/03 23:45:07 Failed to tree: directory not found
```

### PR DESCRIPTION
**Pull request by Cnly**
#### What is the purpose of this change?

This PR fixes #3164, and also adds a unit test to prevent similar failures in the future.

#### Was the change discussed in an issue or in the forum before?

The changes have been discussed and explained in https://github.com/ncw/rclone/issues/3164.

#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

File: fstest/fstests/fstests.go [hunk 1]
```diff
@@ -1583,6 +1583,27 @@ func Run(t *testing.T, opt *Opt) {
...
+		// This test is added after
+		// https://github.com/ncw/rclone/issues/3164.
+		t.Run("FsRootCollapse", func(t *testing.T) {
+			deepRemoteName := subRemoteName + "/deeper/nonexisting/directory"
+			deepRemote, err := fs.NewFs(deepRemoteName)
+			require.NoError(t, err)
+
+			colonIndex := strings.IndexRune(deepRemoteName, ':')
+			firstSlashIndex := strings.IndexRune(deepRemoteName, '/')
+			firstDir := deepRemoteName[colonIndex+1:firstSlashIndex]
```
Comment (golangcibot) [inline fstest/fstests/fstests.go]: File is not `goimports`-ed (from `goimports`)

**Comment by ncw** [comment]
Thanks for that and apologies for the delay!

I'll merge that now - check the integration tests tomorrow morning...

https://pub.rclone.org/integration-tests/current/
