### PR TITLE
fichier: make FolderID int and adjust related code - fixes #3359

### LINKED ISSUE #3359: 1fichier: list error
#### What is the problem you are having with rclone?
Listing dirs from 1fichier 

#### What is your rclone version (output from `rclone version`)
rclone v1.48.0-067-g0a1169e6-beta
- os/arch: linux/amd64
- go version: go1.12.7

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux 4.9.53-5.ph2-esx x86_64

####  Which cloud storage system are you using? (eg Google Drive)
1fichier

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone lsd 1fichier:

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2019/07/19 21:54:56 DEBUG : rclone: Version "v1.48.0-067-g0a1169e6-beta" starting with parameters ["rclone" "lsd" "1fichier:" "-vv"]
2019/07/19 21:54:56 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2019/07/19 21:54:57 ERROR : : error listing: couldn't list folders: json: cannot unmarshal number into Go struct field Folder.pass of type string
2019/07/19 21:54:57 Failed to lsd with 2 errors: last error was: couldn't list folders: json: cannot unmarshal number into Go struct field Folder.pass of type string

### PR DESCRIPTION
**Pull request by buengese**
API now provides folder_id and pass as number which go doens't want to unmarshal into string so make them int instead. Requires a little more converting between string and int because of dir cache but not a big deal.

### CODE REVIEW

File: backend/fichier/api.go [hunk 1]
```diff
@@ -4,8 +4,8 @@ import (
 	"context"
 	"io"
 	"net/http"
-	"regexp"
 	"strconv"
+	"regexp"
```
Comment (golangcibot) [inline backend/fichier/api.go]: File is not `goimports`-ed (from `goimports`)
```suggestion
	"regexp"
	"strconv"
```

File: backend/fichier/structs.go [hunk 2]
```diff
@@ -40,7 +40,7 @@ type GenericOKResponse struct {
 // MakeFolderRequest is the request structure of the corresponding request
 type MakeFolderRequest struct {
 	Name     string `json:"name"`
-	FolderID string `json:"folder_id"`
+	FolderID int `json:"folder_id"`
```
Comment (golangcibot) [inline backend/fichier/structs.go]: File is not `goimports`-ed (from `goimports`)
```suggestion
	FolderID int    `json:"folder_id"`
```

**Comment by ncw** [comment]
Great fix :-)

I was wondering - do we know the range of the integers?  If they are 64 bit then we should be using `int64` as the type.

The code as written at the moment will work fine with 64 bit platforms (where `int` is 64 bit) but could fail on 32 bit platforms where `int` is 32 bits.  There is a reducing number of these, but Raspberry Pi and NAS are both popular targets for rclone.

I see you've

**Comment by buengese** [comment]
To be honest I kinda assumed FolderID would just be an incrementing counter unique to each user and no one would store 2 billion folders however this may not be the case. In my account no ID exceeded 2000000 but you are probably right. Didn't give it that much thought. While you're here you may also take a look at my other changes. Don't want to break anything in your absence.

**Comment by ncw** [comment]
> To be honest I kinda assumed FolderID would just be an incrementing counter unique to each user and no one would store 2 billion folders however this may not be the case.

640k should be enough for everyone :-)

> In my account no ID exceeded 2000000 but you are probably right. Didn't give it that much thought. While you're here you may also take a look at my other changes. Don't want to break anything in your absence.

The underlying type of the JSON is floating point double, which can store integers to 2^56 or so so an int 64 is probably safest. However it may be completely unecessary... Are there any docs we could check?

The changes for this PR look excellent :-)
