### PR TITLE
Fixes 3224

### LINKED ISSUE #3224: sync fails to S3 Glacier and Glacier Deep Archive tiers
Creating an issue to track this bug.
https://forum.rclone.org/t/suspected-bug-in-s3-or-compatible-sync-logic-to-glacier/10187

When syncing from a S3 bucket to a S3 bucket if rclone detects that the source object timestamp has changed and the file is the same size and etag is matching in source and destination it attempts to update the metadata that stores the original modtime.
If the S3 object to be updated (copied) is in Glacier or Glacier Deep Archive tier then updating the modtime updates fails since you can't do a server side copy of an object that is in Glacier tier.
The error message is:
Failed to set modification time: InvalidObjectState: Operation is not valid for the source object's storage class
The behavior should be updated to upload the object with the new modtime rather than attempt to do the server side copy/modtime update.

### PR DESCRIPTION
**Pull request by pharveybattelle**
#### What is the purpose of this change?
Fixes #3224
#### Was the change discussed in an issue or in the forum before?
https://forum.rclone.org/t/suspected-bug-in-s3-or-compatible-sync-logic-to-glacier/10187
#### Checklist

- [x] I have read the [contribution guidelines](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request).
- [x] I have added tests for all changes in this PR if appropriate.
- [x] I have added documentation for the changes if appropriate.
- [x] All commit messages are in [house style](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md#commit-messages).
- [x] I'm done, this Pull Request is ready for review :-)

### CODE REVIEW

File: backend/s3/s3.go [hunk 1]
```diff
@@ -1736,6 +1736,9 @@ func (o *Object) SetModTime(modTime time.Time) error {
 	if o.fs.opt.SSEKMSKeyID != "" {
 		req.SSEKMSKeyId = &o.fs.opt.SSEKMSKeyID
 	}
+	if o.fs.opt.StorageClass == "GLACIER" || o.fs.opt.StorageClass == "DEEP_ARCHIVE" {
+		return fs.ErrorCantSetModTime
```
Comment (golangcibot) [inline backend/s3/s3.go]: File is not `goimports`-ed (from `goimports`)

File: backend/s3/s3.go [hunk 2]
```diff
@@ -47,6 +47,7 @@ import (
 	"github.com/ncw/rclone/lib/rest"
 	"github.com/ncw/swift"
 	"github.com/pkg/errors"
+	"github.com/ncw/rclone/fs"
```
Comment (golangcibot) [inline backend/s3/s3.go]: File is not `goimports`-ed (from `goimports`)

**Comment by ncw** [comment]
That looks great!

Can you add a small bit [to the docs](https://github.com/ncw/rclone/blob/master/docs/content/s3.md#modified-time) 

Maybe something like

> If the modification time needs to be updated, then rclone will use the COPY command to update the metadata in-place.  Note this isn't possible with GLACIER storage, so in this case rclone will have to upload the file again.

**Comment by pharveybattelle** [comment]
> That looks great!
> 
> Can you add a small bit [to the docs](https://github.com/ncw/rclone/blob/master/docs/content/s3.md#modified-time)
> 
> Maybe something like
> 
> > If the modification time needs to be updated, then rclone will use the COPY command to update the metadata in-place.  Note this isn't possible with GLACIER storage, so in this case rclone will have to upload the file again.

done

**Comment by ncw** [comment]
I've merged that now - apologies for the delay.

Thank you very much for that - much appreciated :-)

**Comment by pharveybattelle** [comment]
> I've merged that now - apologies for the delay.
> 
> Thank you very much for that - much appreciated :-)

Thanks ncw for walking me though the process as a noob

**Comment by ncw** [comment]
> Thanks ncw for walking me though the process as a noob

My pleasure!
